### ISSUE TITLE
PHP 8

### ISSUE THREAD

**Issue by hkvstore** [selective-php/samesite-cookie#1]
Can you update composer.json for PHP 8? Thanks.

**Comment by odan** [comment]
Done.

**Comment by hkvstore** [comment]
Thanks. However, since the latest version of Slim requires ``"php": "^7.2 || ^8.0"`` only, it is possible to lower the requirement from PHP 7.3 to 7.2 also?

**Comment by odan** [comment]
The minimum PHP version has been fixed.
